# Generated by Django 3.0.5 on 2020-05-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=50)),
                ('P_price', models.IntegerField()),
                ('P_Description', models.CharField(max_length=300)),
            ],
        ),
    ]
