# Generated by Django 3.0.5 on 2020-05-09 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='p',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
