# Generated by Django 3.0.5 on 2020-06-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
